In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      32               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
362    Female      30           Faridabad    
363    Female      40              Jaipur    
364      Male      30            New Delhi   
365      Male      49               Noida    
366    Female      31           Hyderabad    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
362                                                                                                          
363                                                                                                          
364                                                                                                          
365                                                                                                          
366                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
362  I consider privilege to be having parents and ...                                                                                                                                                 
363  A good health,  supportive family and friends ...                                                                                                                                                 
364                           Pursue what i want to do                                                                                                                                                 
365  To have freedom to pursue my life passions and...                                                                            

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
364    Female      30           Faridabad    
365    Female      40              Jaipur    
366      Male      30            New Delhi   
367      Male      49               Noida    
368    Female      31           Hyderabad    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
364                                                                                                          
365                                                                                                          
366                                                                                                          
367                                                                                                          
368                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
364  I consider privilege to be having parents and ...                                                                                                                                                 
365  A good health,  supportive family and friends ...                                                                                                                                                 
366                           Pursue what i want to do                                                                                                                                                 
367  To have freedom to pursue my life passions and...                                                                            

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
364    Female      30           Faridabad    
365    Female      40              Jaipur    
366      Male      30            New Delhi   
367      Male      49               Noida    
368    Female      31           Hyderabad    

            My current relationship status  
2           Separated, filed for a divorce  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
364                          Never married  
365                          Never married  
366                          Never married  
367  Was married earlier, legally divorced  
368                          Never married  

[367 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
364              1                               0   
365              1                               0   
366              1                               0   
367              0                               0   
368              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
364                                0                    0   
365                                0                    0   
366                                0                    0   
367                                0                    0   
368                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
364                                      0               0  
365                                      0               0  
366                                      0               0  
367                                      1               0  
368                                      0               0  

[367 rows x 6 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
364    Female      30           Faridabad    
365    Female      40              Jaipur    
366      Male      30            New Delhi   
367      Male      49               Noida    
368    Female      31           Hyderabad    

            My current relationship status  
2           Separated, filed for a divorce  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
364                          Never married  
365                          Never married  
366                          Never married  
367  Was married earlier, legally divorced  
368                          Never married  

[367 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
364    Female      30           Faridabad    
365    Female      40              Jaipur    
366      Male      30            New Delhi   
367      Male      49               Noida    
368    Female      31           Hyderabad    

            My current relationship status  
2           Separated, filed for a divorce  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
364                          Never married  
365                          Never married  
366                          Never married  
367  Was married earlier, legally divorced  
368                          Never married  

[367 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(367, 144)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 252  11 316 108 272 342 266  45 165 313  25 331 320  41
  330 278 326 332 247 245 343  48 290 261 156 351 311  24  81 229  26 139
  358 309 181 256 288 333 363 123 354  51 118  97  54  30 122 110 295 128
  262  86 136  84 349 260 231  19  55 325 259 274  75 336 365 114 310 307
  183  42 355 287 265 200 308  52 353 100  32   1  73  18  50 105  27 174
    6 327 185  29  65  12 251 344 258 111 228 301 178 221 291 282 246 121
   96  66  77 345 166 296  83 201  56 244 348 135 237 169 196  36 106 160
  328 340 209 241 143  89  91 194 357  71 163 171 255 219 208 335 352 321
  107 230 184 264 271  21 112 238 104 314  35  53 249 119 173 205 147 214
  142 211 263 141 242  62  76 137  70 191  94  79  37  59 180 315 188 297
  346 257 152   9 101  61  23 324 179 293 361 117 131   8  57 276  60 250
  279  13 126  88  43 319 212 133 236  22  33 170 146 195 199 339 132 130
   46  10 217  14 223 189 299 124 216 213  95 134 269 234 292 192 127 305
  154 273 341 253  16 145  40  85 232 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Mumbai ' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 41 'Bengaluru' 'Never married']


['Male' 50 'Bangalore' 'Widow/ Widower']


['Male' 35 'Delhi' 'Never married']


['Male' 49 'Noida ' 'Was married earlier, legally divorced']


['Male' 40 'Hyderabad/pune' 'Never married']


['Male' 40 'delhi' 

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.90711238  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.22839629  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.90711238  1.         ...  0.          0.
   0.        ]
 ...
 [ 1.         -1.24647043  1.         ...  0.          0.
   0.        ]
 [ 1.          1.97743102  0.         ...  0.          0.
   0.        ]
 [ 0.         -1.07679141  1.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']