In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
378    Female      45              Mumbai    
379      Male      32               Delhi    
380      Male      44       Pune / Mumbai    
381    Female      49           Faridabad    
382      Male      36             Chennai    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
378                                                                                                          
379                                                                                                          
380                                                                                                          
381                                                                                                          
382                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
378  Able to live my life comfortably on my own ter...                                                                                                                                                 
379                                 Supportive family                                                                                                                                                  
380                      Be simple ...its interesting                                                                                                                                                  
381  Well educated,  being Financially independent ...                                                                            

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
380    Female      45              Mumbai    
381      Male      32               Delhi    
382      Male      44       Pune / Mumbai    
383    Female      49           Faridabad    
384      Male      36             Chennai    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
380                                                                                                          
381                                                                                                          
382                                                                                                          
383                                                                                                          
384                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
380  Able to live my life comfortably on my own ter...                                                                                                                                                 
381                                 Supportive family                                                                                                                                                  
382                      Be simple ...its interesting                                                                                                                                                  
383  Well educated,  being Financially independent ...                                                                            

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
380    Female      45              Mumbai    
381      Male      32               Delhi    
382      Male      44       Pune / Mumbai    
383    Female      49           Faridabad    
384      Male      36             Chennai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
380  Was married earlier, legally divorced  
381                          Never married  
382         Separated, filed for a divorce  
383                         Widow/ Widower  
384                          Never married  

[383 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
380                  0              0                               0   
381                  0              1                               0   
382                  0              0                               1   
383                  0              0                               0   
384                  0              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
380                                0                    0   
381                                0                    0   
382                                0                    0   
383                                0                    0   
384                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
380                                      1               0  
381                                      0               0  
382                                      0               0  
383                                      0               1  
384                                      0               0  

[383 rows x 7 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
380    Female      45              Mumbai    
381      Male      32               Delhi    
382      Male      44       Pune / Mumbai    
383    Female      49           Faridabad    
384      Male      36             Chennai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
380  Was married earlier, legally divorced  
381                          Never married  
382         Separated, filed for a divorce  
383                         Widow/ Widower  
384                          Never married  

[383 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
380    Female      45              Mumbai    
381      Male      32               Delhi    
382      Male      44       Pune / Mumbai    
383    Female      49           Faridabad    
384      Male      36             Chennai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
380  Was married earlier, legally divorced  
381                          Never married  
382         Separated, filed for a divorce  
383                         Widow/ Widower  
384                          Never married  

[383 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(383, 145)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 252 316  11 108 372 272 266 342  45 165 313  25 331 278
  320  41 330 343 332 326 245 247 290 156 351  48 261  81  24 311 229  26
  358 309 139 181 256  97 118 363 333 123 354 288  51 122  30 128 295  54
  110 376 262  86  84 136 349  19 381 231 260  75  55 259 325 274 307 114
  310 336 365 308 200  52  42 183 375 287 265 355 174  27   1   6 353 105
   50  73  18  32 100 378 228  29 327 185  12 111  65 251 258 344 246 291
  221 282 373 301 178  83 201 296 121 166  77  66  96 345 106 244  56 348
  380 237  36 196 169 135 143  91 241  89 194 379 107 255 335 357 163 219
  208  71 171 340 209 160 328 352 321 230 314 184 382  53  35 173 249 119
  147 263 211 205 214 142 264 104  21 271 238 112 242 141 137  94  70  79
  191 180  62  76 315  59  37 101 257 297 188 346 152   9 179 324  23  61
   60   8 368 131 276  57 361 117 293 212 319  14 217 146 130 189  46 195
   33 223 132  22 199 236 170 339 133  10 126  43  13  88 250 279 124  95
  377 269 234 299 213 216 134 253 192 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi ' 'Never married']


['Male' 36 'Delhi' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 55 'Gurgaon' 'Separated, not legally divorced']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 41 'Bengaluru' 'Never married']


['Male' 35 'Delhi' 'Never married']


['Male' 50 'Bangalore' 'Widow/ Widower']


['Male' 40 'Bangalore ' 'Never married']


['Male' 40 'Hyderabad/pune' 

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.73617814  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.23772871  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.90232795  0.         ...  0.          0.
   0.        ]
 ...
 [ 1.          1.09146977  0.         ...  0.          0.
   0.        ]
 [ 0.          1.92221882  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.23772871  0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']