In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
450      Male      30              Mumbai    
451      Male      30             Chennai    
452      Male      43              Mumbai    
453      Male      45              Chennai   
454      Male      41            bangalore   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
450                                                                                                          
451                                                                                                          
452                                                                                                          
453                                                                                                          
454                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
450  I have a privilege to have a supportive family...                                                                                                                                                 
451  To do what u want to do and how u want to do i...                                                                                                                                                 
452  To be able to chase your dreams in a job on a ...                                                                                                                                                 
453                                       I have a job                                                                            

In [3]:
dataset.to_csv("dataset.csv")

In [4]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
452      Male      30              Mumbai    
453      Male      30             Chennai    
454      Male      43              Mumbai    
455      Male      45              Chennai   
456      Male      41            bangalore   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
452                                                                                                          
453                                                                                                          
454                                                                                                          
455                                                                                                          
456                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
452  I have a privilege to have a supportive family...                                                                                                                                                 
453  To do what u want to do and how u want to do i...                                                                                                                                                 
454  To be able to chase your dreams in a job on a ...                                                                                                                                                 
455                                       I have a job                                                                            

In [5]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [6]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      33               Mumbai                Legally Separated
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
452      Male      30              Mumbai                     Never married
453      Male      30             Chennai                     Never married
454      Male      43              Mumbai                     Never married
455      Male      45              Chennai  Separated, not legally divorced
456      Male      41            bangalore                    Never married

[455 rows x 4 columns]

In [7]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [9]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [10]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
452                  0              1                               0   
453                  0              1                               0   
454                  0              1                               0   
455                  0              0                               0   
456                  0              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
452                                0                    0   
453                                0                    0   
454                                0                    0   
455                                1                    0   
456                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
452                                      0               0  
453                                      0               0  
454                                      0               0  
455                                      0               0  
456                                      0               0  

[455 rows x 7 columns]

In [11]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [12]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      33               Mumbai                Legally Separated
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
452      Male      30              Mumbai                     Never married
453      Male      30             Chennai                     Never married
454      Male      43              Mumbai                     Never married
455      Male      45              Chennai  Separated, not legally divorced
456      Male      41            bangalore                    Never married

[455 rows x 4 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [14]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      33               Mumbai                Legally Separated
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
452      Male      30              Mumbai                     Never married
453      Male      30             Chennai                     Never married
454      Male      43              Mumbai                     Never married
455      Male      45              Chennai  Separated, not legally divorced
456      Male      41            bangalore                    Never married

[455 rows x 4 columns]

In [15]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [17]:
print(features.shape)

(455, 162)


In [18]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [19]:
row =210
selectedRow = refDataset.iloc[row]

In [20]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 401 109 252 409 424 396  11 316 108 372 272  45 165 266 342
  440  25 313 331 320  41 330 278 385 343 383 332 326 247 245 261 290 156
  351  48  24 311  81 229  26 386 309 358 425 139 452 449 181 256 363 333
  354 123 288  97 118  51 122  30 390  54 295 128 110 376 262  86  84 136
  412 349 454 414 260  19 231 381  75 325 259  55 274 446 336 310 307 114
  365 393  42 183 355 265 375 287 308  52 200 415 353   1 174  27 378  32
  100 447  18 404 105  50  73 441   6 327 185  29 228  12  65 258 251 111
  344 178 453 301 221 282 373 291 246 388  66 443 166 296 121 406  96 435
  345 420  77  83 201  56 348 244 380 428 169 196 237  36 135 411 106 328
  209 340 160  89 241 143 432 194  91 357 335 171 208  71 255 163 219 107
  379 421 321 352 230 184  76 314 271 112 438 238  21 264 104 147 173 142
  408 422 403  53 413 211 249 263 444 382 214 119  35 442 205 242 141  70
  391  94 137  79 191  23  62 315 180  37  59 405 429   9 101 346 152 188
  297 426 257 179 324  61 131   8  57 

In [21]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 47 'New Delhi ' 'Never married']


['Male' 42 'New Delhi ' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 50 'Delhi ' 'Separated, not legally divorced']


['Male' 49 'Bangalore, Karnataka, India' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 44 'Delhi' 'Widow/ Widower']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Mumbai ' 'Never married']


['Male' 43 'Tiruvalla ' 'Never married']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi ' 'Never married']


['Male' 36 'Delhi' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New De

In [22]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [23]:
print(preprocessData(refDataset))

[[ 1.         -0.73092495  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.22702972  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.89889002  0.         ...  0.          0.
   0.        ]
 ...
 [ 1.          0.94872582  0.         ...  0.          0.
   0.        ]
 [ 1.          1.28465597  0.         ...  0.          0.
   0.        ]
 [ 1.          0.61279566  0.         ...  0.          0.
   0.        ]]


In [24]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']