In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
418      Male      31           Chandigarh   
419      Male      28             Kolkata    
420      Male      38                Dhule   
421      Male      32               Delhi    
422      Male      36              Multan    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
418                                                                                                          
419                                                                                                          
420                                                                                                          
421                                                                                                          
422                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
418             Healthy body, family living together.                                                                                                                                                  
419                                 Dependable friends                                                                                                                                                 
420  Live with parents... family is very Conservati...                                                                                                                                                 
421  Able to spend time with family & friends, taki...                                                                            

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
420      Male      31           Chandigarh   
421      Male      28             Kolkata    
422      Male      38                Dhule   
423      Male      32               Delhi    
424      Male      36              Multan    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
420                                                                                                          
421                                                                                                          
422                                                                                                          
423                                                                                                          
424                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
420             Healthy body, family living together.                                                                                                                                                  
421                                 Dependable friends                                                                                                                                                 
422  Live with parents... family is very Conservati...                                                                                                                                                 
423  Able to spend time with family & friends, taki...                                                                            

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence My current relationship status
2        Male      33               Mumbai              Legally Separated
3        Male      36           New Delhi                   Never married
4        Male      32           Bangalore                   Never married
5      Female      33             Gurugram            Was married earlier
6      Female      32               Mumbai                  Never married
..        ...     ...                  ...                            ...
420      Male      31           Chandigarh                  Never married
421      Male      28             Kolkata                   Never married
422      Male      38                Dhule                  Never married
423      Male      32               Delhi                   Never married
424      Male      36              Multan                   Never married

[423 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
420                  0              1                               0   
421                  0              1                               0   
422                  0              1                               0   
423                  0              1                               0   
424                  0              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
420                                0                    0   
421                                0                    0   
422                                0                    0   
423                                0                    0   
424                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
420                                      0               0  
421                                      0               0  
422                                      0               0  
423                                      0               0  
424                                      0               0  

[423 rows x 7 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence My current relationship status
2        Male      33               Mumbai              Legally Separated
3        Male      36           New Delhi                   Never married
4        Male      32           Bangalore                   Never married
5      Female      33             Gurugram            Was married earlier
6      Female      32               Mumbai                  Never married
..        ...     ...                  ...                            ...
420      Male      31           Chandigarh                  Never married
421      Male      28             Kolkata                   Never married
422      Male      38                Dhule                  Never married
423      Male      32               Delhi                   Never married
424      Male      36              Multan                   Never married

[423 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence My current relationship status
2        Male      33               Mumbai              Legally Separated
3        Male      36           New Delhi                   Never married
4        Male      32           Bangalore                   Never married
5      Female      33             Gurugram            Was married earlier
6      Female      32               Mumbai                  Never married
..        ...     ...                  ...                            ...
420      Male      31           Chandigarh                  Never married
421      Male      28             Kolkata                   Never married
422      Male      38                Dhule                  Never married
423      Male      32               Delhi                   Never married
424      Male      36              Multan                   Never married

[423 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(423, 150)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 401 109 252 409 396 316  11 108 372 272 266 165 342  45  25
  313 331 320  41 330 278 343 385 383 326 332 245 247 351 261  48 290 156
   24 311  81 229  26 386 358 309 139 181 256 333 123 354 363 118  97 288
   51 122  30 128 295  54 390 110 376 262  86 136  84 412 349 414 381  19
  260 231  75 259 325  55 274 307 114 310 336 365 393 183  42 375 265 287
  355 415 200  52 308  27 174   1   6 353 105  73  18  50 404 378  32 100
  185 327 228  29 111 258 251  65  12 344 282 373 246 221 291 178 301 166
   77  66 420  96 406 121 296 345 388  83 201 244 348  56 106  36 380 196
  237 169 135 411 194 241  89  91 143 209 160 340 328 208 171 357  71 163
  335 219 255 421 379 107 352 321 230 314  76 184 104  21 238 271 264 112
  211 382 422 403 408 147 142 263 214 413 249 119 205 173  35  53 242 141
   70  79  94 391 191 137  62 180 315  59  37 101 405 152 257 297   9 188
  346 179 324  61  23 131   8 368 361 117 293 276  57  60 212 319 195 199
  189 133  22 130 339 236  46 146 132 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 50 'Delhi ' 'Separated, not legally divorced']


['Male' 49 'Bangalore, Karnataka, India' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 44 'Delhi' 'Widow/ Widower']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 55 'Gurgaon' 'Separated, not legally divorced']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 41 'Bengaluru' 'Never married'

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.72885427  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.22916974  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.89541578  0.         ...  0.          0.
   0.        ]
 ...
 [ 1.          0.10395328  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.89541578  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.22916974  0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']