In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
490    Female      29            Bangalore   
491      Male      39            Banglore    
492      Male      30               Mumbai   
493    Female      33               Mumbai   
494    Female      37       Panjim, Mumbai   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
490                                                                                                          
491                                                                                                          
492                                                                                                          
493                                                                                                          
494                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
490  I am a working professional in IT sector (IT+F...                                                                                                                                                 
491                              Friends, A job I love                                                                                                                                                 
492  Being able to save lives and see happiness on ...                                                                                                                                                 
493  We live in times where we should be aware and ...                                                                            

In [3]:
dataset.to_csv("dataset.csv")

In [4]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
492    Female      29            Bangalore   
493      Male      39            Banglore    
494      Male      30               Mumbai   
495    Female      33               Mumbai   
496    Female      37       Panjim, Mumbai   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
492                                                                                                          
493                                                                                                          
494                                                                                                          
495                                                                                                          
496                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
492  I am a working professional in IT sector (IT+F...                                                                                                                                                 
493                              Friends, A job I love                                                                                                                                                 
494  Being able to save lives and see happiness on ...                                                                                                                                                 
495  We live in times where we should be aware and ...                                                                            

In [5]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [6]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
492    Female      29            Bangalore   
493      Male      39            Banglore    
494      Male      30               Mumbai   
495    Female      33               Mumbai   
496    Female      37       Panjim, Mumbai   

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
492                          Never married  
493         Separated, filed for a divorce  
494                          Never married  
495                          Never married  
496  Was married earlier, legally divorced  

[495 rows x 4 columns]

In [7]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [9]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [10]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
492                  0              1                               0   
493                  0              0                               1   
494                  0              1                               0   
495                  0              1                               0   
496                  0              0                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
492                                0                    0   
493                                0                    0   
494                                0                    0   
495                                0                    0   
496                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
492                                      0               0  
493                                      0               0  
494                                      0               0  
495                                      0               0  
496                                      1               0  

[495 rows x 7 columns]

In [11]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [12]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
492    Female      29            Bangalore   
493      Male      39            Banglore    
494      Male      30               Mumbai   
495    Female      33               Mumbai   
496    Female      37       Panjim, Mumbai   

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
492                          Never married  
493         Separated, filed for a divorce  
494                          Never married  
495                          Never married  
496  Was married earlier, legally divorced  

[495 rows x 4 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [14]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
492    Female      29            Bangalore   
493      Male      39            Banglore    
494      Male      30               Mumbai   
495    Female      33               Mumbai   
496    Female      37       Panjim, Mumbai   

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
492                          Never married  
493         Separated, filed for a divorce  
494                          Never married  
495                          Never married  
496  Was married earlier, legally divorced  

[495 rows x 4 columns]

In [15]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [17]:
print(features.shape)

(495, 170)


In [18]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [19]:
row =210
selectedRow = refDataset.iloc[row]

In [20]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 401 252 409 424 396 463 316  11 108 460 372 272 342 165
  266  45 440 313  25 331 320  41 330 385 278 326 332 383 247 245 343  48
  351 290 156 261  24 311  81 229 386  26 139 256 452 449 181 358 425 309
  288 363 123 354 333  51 390  54  30 122  97 118 110 376 295 128 462 262
   86  84 412 136 381  19 260 231 349 454 414 325 259  55 446 274  75 336
  365 307 310 114 393 183  42 287 265 355 375 308 200 415  52 353 100 378
   32   1 404 441  73  50 469  18 456 105 447 457 327 185 174  27   6  29
  344 258 251  12 111  65 178 301 453 228 388 282 373 467 221 291 246 345
   77 296  66 472 443 420  96 406 435 121 166  56 348 244 201  83 428 196
  237 169  36 135 380 411 106 160 328 209 340  91  89 241 194 143 432 321
  352 357 171 255  71 219 163 335 208 464 230 379 421 107  76 184 264 438
  104 112 271  21 238 314 147 422 173 211 119 444 249 413 142  53 382 442
   35 263 205 214 403 408  23  62  70  79 391 191  94 137 242 141  59  37
  315 180 257 152 346 101 429 188 426 

In [21]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 47 'New Delhi ' 'Never married']


['Male' 42 'New Delhi ' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 50 'Delhi ' 'Separated, not legally divorced']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Bangalore, Karnataka, India' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Widow/ Widower']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Mumbai ' 'Never married']


['Male' 43 'Tiruvalla ' 'Never married']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 42 'Bangalore ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 36 'Delhi' 'Never married']


['Male' 55 'Gurgaon' 'Separated, not legally divorced']


['

In [22]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [23]:
print(preprocessData(refDataset))

[[ 1.         -0.71385894  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.20322285  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.88407098  0.         ...  0.          0.
   0.        ]
 ...
 [ 1.         -1.22449504  0.         ...  0.          0.
   0.        ]
 [ 0.         -0.71385894  0.         ...  0.          0.
   0.        ]
 [ 0.         -0.03301082  0.         ...  0.          0.
   0.        ]]


In [24]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']