In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      32               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
356    Female      32               Mumbai   
357    Female      36            Bangalore   
358    Female      35                Delhi   
359    Female      32            Bengaluru   
360      Male      31            Bangalore   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
356                                                                                                          
357                                                                                                          
358                                                                                                          
359                                                                                                          
360                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
356           A supportive family & dependable friends                                                                                                                                                 
357  Having a supportive family, good health, and b...                                                                                                                                                 
358                                     Job that have                                                                                                                                                  
359   Privilege, to me, means feeling financially s...                                                                            

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
358    Female      32               Mumbai   
359    Female      36            Bangalore   
360    Female      35                Delhi   
361    Female      32            Bengaluru   
362      Male      31            Bangalore   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
358                                                                                                          
359                                                                                                          
360                                                                                                          
361                                                                                                          
362                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
358           A supportive family & dependable friends                                                                                                                                                 
359  Having a supportive family, good health, and b...                                                                                                                                                 
360                                     Job that have                                                                                                                                                  
361   Privilege, to me, means feeling financially s...                                                                            

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
358    Female      32               Mumbai                   Never married
359    Female      36            Bangalore                   Never married
360    Female      35                Delhi                   Never married
361    Female      32            Bengaluru                   Never married
362      Male      31            Bangalore                   Never married

[361 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
358              1                               0   
359              1                               0   
360              1                               0   
361              1                               0   
362              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
358                                0                    0   
359                                0                    0   
360                                0                    0   
361                                0                    0   
362                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
358                                      0               0  
359                                      0               0  
360                                      0               0  
361                                      0               0  
362                                      0               0  

[361 rows x 6 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
358    Female      32               Mumbai                   Never married
359    Female      36            Bangalore                   Never married
360    Female      35                Delhi                   Never married
361    Female      32            Bengaluru                   Never married
362      Male      31            Bangalore                   Never married

[361 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
358    Female      32               Mumbai                   Never married
359    Female      36            Bangalore                   Never married
360    Female      35                Delhi                   Never married
361    Female      32            Bengaluru                   Never married
362      Male      31            Bangalore                   Never married

[361 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(361, 143)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 252  11 316 108 272 165 342  45 266  25 313 331 320  41
  330 278 332 326 247 245 343 290 351  48 156 261  24 311  81  26 229 139
  181 309 358 256 288 354 333 123  51  54  97 118 122  30 110 128 295 262
   84 136  86 349  19 231 260  55 325 259 274  75 336 307 310 114  42 183
  287 355 265 308  52 200 353 100  32   1  18  50  73 105 174  27 327 185
    6  29  12 258 111  65 344 251 228 178 301 282 291 246 221  77 166 121
   96 345  66 296 244  56 348  83 201 196  36 169 237 135 106 328 340 160
  209  89 194  91 143 241 335 255 208 357 163 171 219  71 321 352 107 230
  184 271 112 104 264  21 238 314  53 119 147 142 211 249 205 173 263 214
   35 141 242  76  62  70 191  79 137  94  37  59 180 315 257   9 297 101
  188 346 152  61  23 324 179 293 276 117  57   8 131  60 279 126  88  43
  250  13 319 212 130 195 223 146 339 217 132  22 133  14  10 170  46 189
  199 236  33 299  95 134 234 213 124 216 269 273 292 305 192 127 341 154
  145 253  16  72 285 329 232  85 233 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi ' 'Never married']


['Male' 36 'Delhi' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 41 'Bengaluru' 'Never married']


['Male' 50 'Bangalore' 'Widow/ Widower']


['Male' 35 'Delhi' 'Never married']


['Male' 40 'Bangalore ' 'Never married']


['Male' 40 'delhi' 'Was married earlier']


['Male' 40 'Hyderabad/pune' 'Never married

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.91529088  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.23401251  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.91529088  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.40433211  1.         ...  0.          0.
   0.        ]
 [ 0.         -0.91529088  1.         ...  0.          0.
   0.        ]
 [ 1.         -1.08561048  1.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']