In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
406      Male      38             Gurgaon    
407    Female      28            New Delhi   
408      Male      36            Bangalore   
409    Female      38                Delhi   
410    Female      33           Bangalore    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
406                                                                                                          
407                                                                                                          
408                                                                                                          
409                                                                                                          
410                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
406  Have a clear mind, conscience, family values, ...                                                                                                                                                 
407  when we have a loving and understanding family...                                                                                                                                                 
408     I consider I'm privileged to be around horses                                                                                                                                                  
409  Having a supportive family, spiritual connect ...                                                                            

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
408      Male      38             Gurgaon    
409    Female      28            New Delhi   
410      Male      36            Bangalore   
411    Female      38                Delhi   
412    Female      33           Bangalore    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
408                                                                                                          
409                                                                                                          
410                                                                                                          
411                                                                                                          
412                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
408  Have a clear mind, conscience, family values, ...                                                                                                                                                 
409  when we have a loving and understanding family...                                                                                                                                                 
410     I consider I'm privileged to be around horses                                                                                                                                                  
411  Having a supportive family, spiritual connect ...                                                                            

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
408      Male      38             Gurgaon    
409    Female      28            New Delhi   
410      Male      36            Bangalore   
411    Female      38                Delhi   
412    Female      33           Bangalore    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
408                          Never married  
409                          Never married  
410                          Never married  
411                          Never married  
412  Was married earlier, legally divorced  

[411 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
408                  0              1                               0   
409                  0              1                               0   
410                  0              1                               0   
411                  0              1                               0   
412                  0              0                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
408                                0                    0   
409                                0                    0   
410                                0                    0   
411                                0                    0   
412                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
408                                      0               0  
409                                      0               0  
410                                      0               0  
411                                      0               0  
412                                      1               0  

[411 rows x 7 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
408      Male      38             Gurgaon    
409    Female      28            New Delhi   
410      Male      36            Bangalore   
411    Female      38                Delhi   
412    Female      33           Bangalore    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
408                          Never married  
409                          Never married  
410                          Never married  
411                          Never married  
412  Was married earlier, legally divorced  

[411 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
408      Male      38             Gurgaon    
409    Female      28            New Delhi   
410      Male      36            Bangalore   
411    Female      38                Delhi   
412    Female      33           Bangalore    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
408                          Never married  
409                          Never married  
410                          Never married  
411                          Never married  
412  Was married earlier, legally divorced  

[411 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(411, 146)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 401 252 409 396  11 316 108 372 272 342  45 266 165 313
   25 331 320  41 330 278 343 385 332 383 326 247 245 290 261  48 351 156
  311  24  81 229 386  26 309 358 139 181 256 118  97 123 363 354 333 288
   51  30 122 128 295  54 390 110 376 262  86 136  84 349 231 260 381  19
   75 259 325  55 274 114 307 310 336 365 393  52 308 200 183  42 287 265
  355 375  27 174   6   1 353 404  73  18  50 105 378 100  32 185 327 228
   29  65 251 344 111 258  12 246 221 282 291 373 301 178 166  77 296 121
  406  96 345  66 201  83 388 106 348  56 244 380 135  36 237 196 169  91
   89 241 194 143 107 379 328 340 209 160 335 163 357 255 171 208  71 219
  352 321 230 314 184  76 112 238 271 104 264  21 119 249 142 214  53 408
  173 403 211 205  35 263 147 382 141 242  94 137  79 191 391  70  62 180
  315  59  37   9 188 152 257 297 101 405 346 179  23 324  61  60 117 131
  276   8 361 368  57 293 212 319 189 195 236 339 223 132 133 170  46 199
  217  22  33 130  14  10 146  13 126 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 50 'Delhi ' 'Separated, not legally divorced']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Bangalore, Karnataka, India' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Mumbai ' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Widow/ Widower']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 55 'Gurgaon' 'Separated, not legally divorced']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 41 'Bengaluru' 'Never married'

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.73168739  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.23325062  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.89783299  0.         ...  0.          0.
   0.        ]
 ...
 [ 1.         -0.23325062  0.         ...  0.          0.
   0.        ]
 [ 0.          0.09904056  0.         ...  0.          0.
   0.        ]
 [ 0.         -0.73168739  0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']