In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      32               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
168      Male      29             Gurgaon    
169      Male      44             Gurgaon    
170      Male      34             Gurugram   
171    Female      36             Gurugram   
172    Female      32            Bangalore   

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
0                   Having things that money cant buy.                                                         
1                                      Family,friends                                                          
2                   Supportive/understandable/Friendly                                                         
3      Being able to love people and be loved by them                                                          
4      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
168  A good family, have some good supportive frien...                                                         
169                                     Have this life                                                         
170  To cultivate so much self awareness to be your...                                                         
171                  Able to live life on my own terms                                                         
172  Growing up without financial struggles, Having...                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
0    Defense upbringing, kept moving cities and sch...                                                                                             
1                                             Awesome                                                                                              
2                 Awesome & challenging, All Good Now.                                                                                             
3    We’re full of curiosity and learning I was an ...                                                                                             
4    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
168  Life is pretty good with ups and downs but the...                                                                                             
169                                            Lonely                                                                                              
170  My growing up years were a bit challenging but...                                                                                             
171  A mixed bag pf good times and bad. Military ki...                                                                                             
172  I grew up in a liberal values household, with ...                                                                                             

     My current relationship status I have children  \
0    Separated, filed for a divorce              No   
1                     Never married              No   
2                     Never married              No   
3               Was married earlier              No   
4                     Never married              No   

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
170      Male      29             Gurgaon    
171      Male      44             Gurgaon    
172      Male      34             Gurugram   
173    Female      36             Gurugram   
174    Female      32            Bangalore   

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
2                   Having things that money cant buy.                                                         
3                                      Family,friends                                                          
4                   Supportive/understandable/Friendly                                                         
5      Being able to love people and be loved by them                                                          
6      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
170  A good family, have some good supportive frien...                                                         
171                                     Have this life                                                         
172  To cultivate so much self awareness to be your...                                                         
173                  Able to live life on my own terms                                                         
174  Growing up without financial struggles, Having...                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
2    Defense upbringing, kept moving cities and sch...                                                                                             
3                                             Awesome                                                                                              
4                 Awesome & challenging, All Good Now.                                                                                             
5    We’re full of curiosity and learning I was an ...                                                                                             
6    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
170  Life is pretty good with ups and downs but the...                                                                                             
171                                            Lonely                                                                                              
172  My growing up years were a bit challenging but...                                                                                             
173  A mixed bag pf good times and bad. Military ki...                                                                                             
174  I grew up in a liberal values household, with ...                                                                                             

     My current relationship status I have children  \
2    Separated, filed for a divorce              No   
3                     Never married              No   
4                     Never married              No   
5               Was married earlier              No   
6                     Never married              No   

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

In [5]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
170      Male      29             Gurgaon                    Never married
171      Male      44             Gurgaon              Was married earlier
172      Male      34             Gurugram                   Never married
173    Female      36             Gurugram                   Never married
174    Female      32            Bangalore             Was married earlier

[173 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
170              1                               0   
171              0                               0   
172              1                               0   
173              1                               0   
174              0                               0   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
2                                  0                    0               0  
3                                  0                    0               0  
4                                  0                    0               0  
5                                  0                    1               0  
6                                  0                    0               0  
..                               ...                  ...             ...  
170                                0                    0               0  
171                                0                    1               0  
172                                0                    0               0  
173                                0                    0               0  
174                                0                    1               0  

[173 rows x 5 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
170      Male      29             Gurgaon                    Never married
171      Male      44             Gurgaon              Was married earlier
172      Male      34             Gurugram                   Never married
173    Female      36             Gurugram                   Never married
174    Female      32            Bangalore             Was married earlier

[173 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
170      Male      29             Gurgaon                    Never married
171      Male      44             Gurgaon              Was married earlier
172      Male      34             Gurugram                   Never married
173    Female      36             Gurugram                   Never married
174    Female      32            Bangalore             Was married earlier

[173 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(173, 50)


In [17]:
k =100
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=100)

In [19]:
row =172
selectedRow = refDataset.iloc[row]

In [20]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[172  34  98 164  87  47 162 115  93   5  31  16 154  58  74   3  15 120
   57  17  68 129 140   2  69  78  70 137  82  99  22 146  33 163   9  20
  152 125 148  80 160 147   7  90  64 158 157 168  37  72 116 102  89 150
  144 149  38 106   4  63 141 151 155 159  96 138  88  13  43   0 107 167
   60 103  44   6 145 127 134  18 124  95  40  49 153  85 117 131   8  59
   10  46 130 133 132 170  14  27  23  79]]


In [21]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 33 'Bangalore' 'Was married earlier']


['Male' 29 'Bangalore ' 'Never married']


['Male' 31 'Bangalore' 'Never married']


['Male' 31 'Bangalore ' 'Never married']


['Male' 32 'Bangalore' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 33 'Vadodara' 'Was married earlier']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 35 'Bangalore ' 'Never married']


['Male' 35 'Hyderabad' 'Was married earlier']


['Male' 35 'Bangalore' 'Never married']


['Male' 35 'Pune' 'Was married earlier']


['Male' 35 'Chennai' 'Was married earlier']


['Male' 36 'Bangalore ' 'Never married']


['Male' 36 'Bangalore' 'Separated, filed for a divorce']


['Male' 36 'Bengaluru ' 'Was married earlier']


['Male' 36 'Bengaluru' 'Was married earlier']


['Male' 29 'Mumbai ' 'Never married']


['Male' 29 'Gurgaon

In [ ]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [ ]:
print(preprocessData(refDataset))

In [22]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']