In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age        My city of residence  \
0        Male      32                      Mumbai   
1        Male      36                  New Delhi    
2        Male      32                  Bangalore    
3      Female      33                    Gurugram   
4      Female      32                      Mumbai   
..        ...     ...                         ...   
174      Male      34                       Delhi   
175      Male      30                   Bangalore   
176    Female      29                   Gurugram    
177      Male      34                     Gurgaon   
178      Male      45  Hyderabad Telangana India    

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
0                   Having things that money cant buy.                                                         
1                                      Family,friends                                                          
2                   Supportive/understandable/Friendly                                                         
3      Being able to love people and be loved by them                                                          
4      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
174  Privilege, as defined, is the ability to achie...                                                         
175  not caring about what society imposes on you t...                                                         
176                         Having a supportive family                                                         
177                               Having good friends                                                          
178                                      I love my job                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
0    Defense upbringing, kept moving cities and sch...                                                                                             
1                                             Awesome                                                                                              
2                 Awesome & challenging, All Good Now.                                                                                             
3    We’re full of curiosity and learning I was an ...                                                                                             
4    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
174  Growing up, I had an encouraging family that a...                                                                                             
175  I am still growing up and it has and will be a...                                                                                             
176  Challenges are in every phase of life, but you...                                                                                             
177  Were amazing had good experience with family w...                                                                                             
178                              I am family oriented                                                                                              

      My current relationship status I have children  \
0     Separated, filed for a divorce              No   
1                      Never married              No   
2                      Never married              No   
3                Was 

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age        My city of residence  \
2        Male      32                      Mumbai   
3        Male      36                  New Delhi    
4        Male      32                  Bangalore    
5      Female      33                    Gurugram   
6      Female      32                      Mumbai   
..        ...     ...                         ...   
176      Male      34                       Delhi   
177      Male      30                   Bangalore   
178    Female      29                   Gurugram    
179      Male      34                     Gurgaon   
180      Male      45  Hyderabad Telangana India    

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
2                   Having things that money cant buy.                                                         
3                                      Family,friends                                                          
4                   Supportive/understandable/Friendly                                                         
5      Being able to love people and be loved by them                                                          
6      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
176  Privilege, as defined, is the ability to achie...                                                         
177  not caring about what society imposes on you t...                                                         
178                         Having a supportive family                                                         
179                               Having good friends                                                          
180                                      I love my job                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
2    Defense upbringing, kept moving cities and sch...                                                                                             
3                                             Awesome                                                                                              
4                 Awesome & challenging, All Good Now.                                                                                             
5    We’re full of curiosity and learning I was an ...                                                                                             
6    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
176  Growing up, I had an encouraging family that a...                                                                                             
177  I am still growing up and it has and will be a...                                                                                             
178  Challenges are in every phase of life, but you...                                                                                             
179  Were amazing had good experience with family w...                                                                                             
180                              I am family oriented                                                                                              

      My current relationship status I have children  \
2     Separated, filed for a divorce              No   
3                      Never married              No   
4                      Never married              No   
5                Was 

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

In [5]:
dataset

My Gender  My age        My city of residence  \
2        Male      32                      Mumbai   
3        Male      36                  New Delhi    
4        Male      32                  Bangalore    
5      Female      33                    Gurugram   
6      Female      32                      Mumbai   
..        ...     ...                         ...   
176      Male      34                       Delhi   
177      Male      30                   Bangalore   
178    Female      29                   Gurugram    
179      Male      34                     Gurgaon   
180      Male      45  Hyderabad Telangana India    

      My current relationship status  
2     Separated, filed for a divorce  
3                      Never married  
4                      Never married  
5                Was married earlier  
6                      Never married  
..                               ...  
176                    Never married  
177                    Never married  
178                    Never married  
179  Separated, not legally divorced  
180  Separated, not legally divorced  

[179 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
176              1                               0   
177              1                               0   
178              1                               0   
179              0                               0   
180              0                               0   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
2                                  0                    0               0  
3                                  0                    0               0  
4                                  0                    0               0  
5                                  0                    1               0  
6                                  0                    0               0  
..                               ...                  ...             ...  
176                                0                    0               0  
177                                0                    0               0  
178                                0                    0               0  
179                                1                    0               0  
180                                1                    0               0  

[179 rows x 5 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age        My city of residence  \
2        Male      32                      Mumbai   
3        Male      36                  New Delhi    
4        Male      32                  Bangalore    
5      Female      33                    Gurugram   
6      Female      32                      Mumbai   
..        ...     ...                         ...   
176      Male      34                       Delhi   
177      Male      30                   Bangalore   
178    Female      29                   Gurugram    
179      Male      34                     Gurgaon   
180      Male      45  Hyderabad Telangana India    

      My current relationship status  
2     Separated, filed for a divorce  
3                      Never married  
4                      Never married  
5                Was married earlier  
6                      Never married  
..                               ...  
176                    Never married  
177                    Never married  
178                    Never married  
179  Separated, not legally divorced  
180  Separated, not legally divorced  

[179 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age        My city of residence  \
2        Male      32                      Mumbai   
3        Male      36                  New Delhi    
4        Male      32                  Bangalore    
5      Female      33                    Gurugram   
6      Female      32                      Mumbai   
..        ...     ...                         ...   
176      Male      34                       Delhi   
177      Male      30                   Bangalore   
178    Female      29                   Gurugram    
179      Male      34                     Gurgaon   
180      Male      45  Hyderabad Telangana India    

      My current relationship status  
2     Separated, filed for a divorce  
3                      Never married  
4                      Never married  
5                Was married earlier  
6                      Never married  
..                               ...  
176                    Never married  
177                    Never married  
178                    Never married  
179  Separated, not legally divorced  
180  Separated, not legally divorced  

[179 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(179, 52)


In [17]:
k =100
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=100)

In [18]:
row =172
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[172  34  98 164  47  87 162 115   5  93  31  16 154  74  58   3  15 175
   57 120  68  17 140 129   2  69  70 137  78  82  99  22  33 146 163   9
  148 125 152  20  80 160   7  90  64 147 176 158 157 168  37  72  89 116
  150 102 144  38 149 106   4 151 141 159 155  63 138  96  88  43  13  44
  107   0  60 103 167 145 127   6 134  18 124  95  49 153  40  85 131   8
  117  59  14  10 130 170  46 132 174 133]]


In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 33 'Bangalore' 'Was married earlier']


['Male' 29 'Bangalore ' 'Never married']


['Male' 30 'Bangalore' 'Never married']


['Male' 31 'Bangalore ' 'Never married']


['Male' 31 'Bangalore' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 33 'Vadodara' 'Was married earlier']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 35 'Bangalore ' 'Never married']


['Male' 35 'Chennai' 'Was married earlier']


['Male' 35 'Pune' 'Was married earlier']


['Male' 35 'Bangalore' 'Never married']


['Male' 35 'Hyderabad' 'Was married earlier']


['Male' 36 'Bangalore' 'Separated, filed for a divorce']


['Male' 36 'Bengaluru ' 'Was married earlier']


['Male' 36 'Bengaluru' 'Was married earlier']


['Male' 36 'Bangalore ' 'Never married']


['Male' 29 'Mumba

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.92733222  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.19929508  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.92733222  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -1.47336007  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.56331365  0.         ...  0.          0.
   0.        ]
 [ 1.          1.43878847  0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']