In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age   My city of residence  \
0        Male      32                 Mumbai   
1        Male      36             New Delhi    
2        Male      32             Bangalore    
3      Female      33               Gurugram   
4      Female      32                 Mumbai   
..        ...     ...                    ...   
180    Female      33  Ghaziabad (Delhi-NCR)   
181      Male      43                  Delhi   
182      Male      32       HYDERABAD, INDIA   
183      Male      48              Bangalore   
184      Male      42             Bangalore    

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
0                   Having things that money cant buy.                                                         
1                                      Family,friends                                                          
2                   Supportive/understandable/Friendly                                                         
3      Being able to love people and be loved by them                                                          
4      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
180  I’m privileged to have a supportive family and...                                                         
181                                      Well wishers                                                          
182  Primarily HAVING TO DO WHATEVER YOU LOVE DOING...                                                         
183                             Loved and acknowledged                                                         
184                     supportive family and friends                                                          

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
0    Defense upbringing, kept moving cities and sch...                                                                                             
1                                             Awesome                                                                                              
2                 Awesome & challenging, All Good Now.                                                                                             
3    We’re full of curiosity and learning I was an ...                                                                                             
4    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
180  I grew up in a joint family which has it's own...                                                                                             
181                                            Memory                                                                                              
182  Priviliged, had lots of fun, nothing much to c...                                                                                             
183                                            Awesome                                                                                             
184                                 They were awesome                                                                                              

      My current relationship status I have children  \
0     Separated, filed for a divorce              No   
1                      Never married              No   
2                      Never married              No   
3                Was married earlier              No   
4                      Ne

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age   My city of residence  \
2        Male      32                 Mumbai   
3        Male      36             New Delhi    
4        Male      32             Bangalore    
5      Female      33               Gurugram   
6      Female      32                 Mumbai   
..        ...     ...                    ...   
182    Female      33  Ghaziabad (Delhi-NCR)   
183      Male      43                  Delhi   
184      Male      32       HYDERABAD, INDIA   
185      Male      48              Bangalore   
186      Male      42             Bangalore    

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
2                   Having things that money cant buy.                                                         
3                                      Family,friends                                                          
4                   Supportive/understandable/Friendly                                                         
5      Being able to love people and be loved by them                                                          
6      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
182  I’m privileged to have a supportive family and...                                                         
183                                      Well wishers                                                          
184  Primarily HAVING TO DO WHATEVER YOU LOVE DOING...                                                         
185                             Loved and acknowledged                                                         
186                     supportive family and friends                                                          

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
2    Defense upbringing, kept moving cities and sch...                                                                                             
3                                             Awesome                                                                                              
4                 Awesome & challenging, All Good Now.                                                                                             
5    We’re full of curiosity and learning I was an ...                                                                                             
6    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
182  I grew up in a joint family which has it's own...                                                                                             
183                                            Memory                                                                                              
184  Priviliged, had lots of fun, nothing much to c...                                                                                             
185                                            Awesome                                                                                             
186                                 They were awesome                                                                                              

      My current relationship status I have children  \
2     Separated, filed for a divorce              No   
3                      Never married              No   
4                      Never married              No   
5                Was married earlier              No   
6                      Ne

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

In [5]:
dataset

My Gender  My age   My city of residence   My current relationship status
2        Male      32                 Mumbai   Separated, filed for a divorce
3        Male      36             New Delhi                     Never married
4        Male      32             Bangalore                     Never married
5      Female      33               Gurugram              Was married earlier
6      Female      32                 Mumbai                    Never married
..        ...     ...                    ...                              ...
182    Female      33  Ghaziabad (Delhi-NCR)                    Never married
183      Male      43                  Delhi              Was married earlier
184      Male      32       HYDERABAD, INDIA                    Never married
185      Male      48              Bangalore  Separated, not legally divorced
186      Male      42             Bangalore   Separated, not legally divorced

[185 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
182              1                               0   
183              0                               0   
184              1                               0   
185              0                               0   
186              0                               0   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
2                                  0                    0               0  
3                                  0                    0               0  
4                                  0                    0               0  
5                                  0                    1               0  
6                                  0                    0               0  
..                               ...                  ...             ...  
182                                0                    0               0  
183                                0                    1               0  
184                                0                    0               0  
185                                1                    0               0  
186                                1                    0               0  

[185 rows x 5 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age   My city of residence   My current relationship status
2        Male      32                 Mumbai   Separated, filed for a divorce
3        Male      36             New Delhi                     Never married
4        Male      32             Bangalore                     Never married
5      Female      33               Gurugram              Was married earlier
6      Female      32                 Mumbai                    Never married
..        ...     ...                    ...                              ...
182    Female      33  Ghaziabad (Delhi-NCR)                    Never married
183      Male      43                  Delhi              Was married earlier
184      Male      32       HYDERABAD, INDIA                    Never married
185      Male      48              Bangalore  Separated, not legally divorced
186      Male      42             Bangalore   Separated, not legally divorced

[185 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age   My city of residence   My current relationship status
2        Male      32                 Mumbai   Separated, filed for a divorce
3        Male      36             New Delhi                     Never married
4        Male      32             Bangalore                     Never married
5      Female      33               Gurugram              Was married earlier
6      Female      32                 Mumbai                    Never married
..        ...     ...                    ...                              ...
182    Female      33  Ghaziabad (Delhi-NCR)                    Never married
183      Male      43                  Delhi              Was married earlier
184      Male      32       HYDERABAD, INDIA                    Never married
185      Male      48              Bangalore  Separated, not legally divorced
186      Male      42             Bangalore   Separated, not legally divorced

[185 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(185, 52)


In [17]:
k =100
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=100)

In [18]:
row =172
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[172  34  98 164  87  47 162 115   5  93  31 154  16  74  58   3  15 175
   57 120  68  17 129   2 140  69  78 137  70  82  99  22  33 146 163  20
  125 152   9 148  80 160   7  90 147  64 158 176  37 157 168  72 116  89
  102 150 144 149  38   4 106 155 151  63 159 141  96 138  13  88  43 179
   44 167 107   0  60 182 103 145 180   6 127 134 124  95  18 153  40  85
   49 117   8 131  59 130 132 177  46  14]]


In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 33 'Bangalore' 'Was married earlier']


['Male' 29 'Bangalore ' 'Never married']


['Male' 30 'Bangalore' 'Never married']


['Male' 31 'Bangalore ' 'Never married']


['Male' 31 'Bangalore' 'Never married']


['Male' 32 'Bangalore' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 32 'Bangalore ' 'Never married']


['Male' 33 'Vadodara' 'Was married earlier']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 34 'Bangalore' 'Never married']


['Male' 35 'Hyderabad' 'Was married earlier']


['Male' 35 'Pune' 'Was married earlier']


['Male' 35 'Bangalore' 'Never married']


['Male' 35 'Bangalore ' 'Never married']


['Male' 35 'Chennai' 'Was married earlier']


['Male' 36 'Bangalore' 'Separated, filed for a divorce']


['Male' 36 'Bengaluru ' 'Was married earlier']


['Male' 36 'Bangalore ' 'Never married']


['Male' 36 'Bengaluru' 'Was married earlier']


['Male' 29 'Mumba

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.92924035  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.20541102  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.92924035  1.         ...  0.          0.
   0.        ]
 ...
 [ 1.         -0.92924035  1.         ...  0.          0.
   0.        ]
 [ 1.          1.96607695  0.         ...  0.          0.
   0.        ]
 [ 1.          0.88033296  0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']