In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      32               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
323    Female      37            Bangalore   
324      Male      40               Noida    
325    Female      48                 Pune   
326      Male      49                 Pune   
327      Male      46  Vaishali, Ghaziabad   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
323                                                                                                          
324                                                                                                          
325                                                                                                          
326                                                                                                          
327                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
323  Having someone who care for you in any given s...                                                                                                                                                 
324              Have a supportive family and friends                                                                                                                                                  
325  Just to be breathing every day and having a pe...                                                                                                                                                 
326  Human Life and our ability to make it beautiful!                                                                             

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
325    Female      37            Bangalore   
326      Male      40               Noida    
327    Female      48                 Pune   
328      Male      49                 Pune   
329      Male      46  Vaishali, Ghaziabad   

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
325                                                                                                          
326                                                                                                          
327                                                                                                          
328                                                                                                          
329                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
325  Having someone who care for you in any given s...                                                                                                                                                 
326              Have a supportive family and friends                                                                                                                                                  
327  Just to be breathing every day and having a pe...                                                                                                                                                 
328  Human Life and our ability to make it beautiful!                                                                             

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [5]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      32               Mumbai   Separated, filed for a divorce
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
325    Female      37            Bangalore              Was married earlier
326      Male      40               Noida    Separated, filed for a divorce
327    Female      48                 Pune              Was married earlier
328      Male      49                 Pune                    Never married
329      Male      46  Vaishali, Ghaziabad  Separated, not legally divorced

[328 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
325              0                               0   
326              0                               1   
327              0                               0   
328              1                               0   
329              0                               0   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
2                                  0                    0               0  
3                                  0                    0               0  
4                                  0                    0               0  
5                                  0                    1               0  
6                                  0                    0               0  
..                               ...                  ...             ...  
325                                0                    1               0  
326                                0                    0               0  
327                                0                    1               0  
328                                0                    0               0  
329                                1                    0               0  

[328 rows x 5 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      32               Mumbai   Separated, filed for a divorce
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
325    Female      37            Bangalore              Was married earlier
326      Male      40               Noida    Separated, filed for a divorce
327    Female      48                 Pune              Was married earlier
328      Male      49                 Pune                    Never married
329      Male      46  Vaishali, Ghaziabad  Separated, not legally divorced

[328 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence   My current relationship status
2        Male      32               Mumbai   Separated, filed for a divorce
3        Male      36           New Delhi                     Never married
4        Male      32           Bangalore                     Never married
5      Female      33             Gurugram              Was married earlier
6      Female      32               Mumbai                    Never married
..        ...     ...                  ...                              ...
325    Female      37            Bangalore              Was married earlier
326      Male      40               Noida    Separated, filed for a divorce
327    Female      48                 Pune              Was married earlier
328      Male      49                 Pune                    Never married
329      Male      46  Vaishali, Ghaziabad  Separated, not legally divorced

[328 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(328, 139)


In [17]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [18]:
row =210
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 109 252  11 316 108 272 165  45 266 313  25 320  41 278 326
  245 247 156 290  48 261  24 311  81 229  26 139 309 181 256 288 123  51
   54 118  97 122  30 110 295 128 262 136  84  86  19 231 260 325  55 259
  274  75 310 307 114 183  42 287 265 200 308  52  32 100  18 105  50  73
    1  27 174 327 185   6  29 258 111  12  65 251 228 301 178 282 291 246
  221 166 296 121  96  66  77  56 244  83 201  36 196 169 135 237 106 209
  160  91 241  89 143 194 163  71 171 208 219 255 321 107 230 184 238  21
  112 264 271 104 314 119 173 214 211  35 205 142  53 263 147 249  62  76
  141 242  70  94 191 137  79  59  37 180 315 188 257 101   9 297 152  23
  324  61 179 276   8  57 131 117 293  60 126  43 279 250  13  88 130 223
   33 199  22 217  10 236 189 133  46  14 132 146 170 195 319 212 234 216
  124 134 299 213  95 269 127 253 154 273 305 292 192 145  16  72 285 153
   85 233 232  40  49 138 222 294  39  38 225  44 103 140 284 167 203 129
  190 182  69   2 317   4 267 102 204 

In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 45 'New Delhi ' 'Was married earlier']


['Male' 50 'Bangalore' 'Widow/ Widower']


['Male' 35 'Delhi' 'Never married']


['Male' 40 'delhi' 'Was married earlier']


['Male' 40 'Bangalore ' 'Never married']


['Male' 40 'Hyderabad/pune' 'Never married']


['Male' 48 'Bangalore' 'Separated, not legally divorced']


['Male' 48 'Mu

In [21]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [22]:
print(preprocessData(refDataset))

[[ 1.         -0.88707346  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.20963436  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.88707346  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.          1.82268295  0.         ...  0.          0.
   0.        ]
 [ 1.          1.99204272  1.         ...  0.          0.
   0.        ]
 [ 1.          1.4839634   0.         ...  0.          0.
   0.        ]]


In [23]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']