In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      32               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
155      Male      31               Mumbai   
156    Female      42                Delhi   
157      Male      29              Mumbai    
158    Female      29              Gurgaon   
159      Male      31            New Delhi   

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
0                   Having things that money cant buy.                                                         
1                                      Family,friends                                                          
2                   Supportive/understandable/Friendly                                                         
3      Being able to love people and be loved by them                                                          
4      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
155  Having a supportive family, dependable friends...                                                         
156  Having supportive, loving family, friends, a c...                                                         
157        Having understanding and supporting family                                                          
158  Both what I am born with, and what I have crea...                                                         
159                        Having a Supportive Family.                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
0    Defense upbringing, kept moving cities and sch...                                                                                             
1                                             Awesome                                                                                              
2                 Awesome & challenging, All Good Now.                                                                                             
3    We’re full of curiosity and learning I was an ...                                                                                             
4    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
155  There were ups & downs but at the end it was a...                                                                                             
156       I had a lovely childhood growing up in delhi                                                                                             
157  It was challenging and struggling but with fam...                                                                                             
158  Growing up was a mixed journey. While I had a ...                                                                                             
159  1. I was raised in a family of entrepreneurs. ...                                                                                             

     My current relationship status I have children  \
0    Separated, filed for a divorce              No   
1                     Never married              No   
2                     Never married              No   
3               Was married earlier              No   
4                     Never married              No   

In [3]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      32               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
157      Male      31               Mumbai   
158    Female      42                Delhi   
159      Male      29              Mumbai    
160    Female      29              Gurgaon   
161      Male      31            New Delhi   

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
2                   Having things that money cant buy.                                                         
3                                      Family,friends                                                          
4                   Supportive/understandable/Friendly                                                         
5      Being able to love people and be loved by them                                                          
6      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
157  Having a supportive family, dependable friends...                                                         
158  Having supportive, loving family, friends, a c...                                                         
159        Having understanding and supporting family                                                          
160  Both what I am born with, and what I have crea...                                                         
161                        Having a Supportive Family.                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
2    Defense upbringing, kept moving cities and sch...                                                                                             
3                                             Awesome                                                                                              
4                 Awesome & challenging, All Good Now.                                                                                             
5    We’re full of curiosity and learning I was an ...                                                                                             
6    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
157  There were ups & downs but at the end it was a...                                                                                             
158       I had a lovely childhood growing up in delhi                                                                                             
159  It was challenging and struggling but with fam...                                                                                             
160  Growing up was a mixed journey. While I had a ...                                                                                             
161  1. I was raised in a family of entrepreneurs. ...                                                                                             

     My current relationship status I have children  \
2    Separated, filed for a divorce              No   
3                     Never married              No   
4                     Never married              No   
5               Was married earlier              No   
6                     Never married              No   

In [4]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

In [5]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
157      Male      31               Mumbai                   Never married
158    Female      42                Delhi             Was married earlier
159      Male      29              Mumbai                    Never married
160    Female      29              Gurgaon                   Never married
161      Male      31            New Delhi  Separated, filed for a divorce

[160 rows x 4 columns]

In [6]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [8]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [9]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
2                0                               1   
3                1                               0   
4                1                               0   
5                0                               0   
6                1                               0   
..             ...                             ...   
157              1                               0   
158              0                               0   
159              1                               0   
160              1                               0   
161              0                               1   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
2                                  0                    0               0  
3                                  0                    0               0  
4                                  0                    0               0  
5                                  0                    1               0  
6                                  0                    0               0  
..                               ...                  ...             ...  
157                                0                    0               0  
158                                0                    1               0  
159                                0                    0               0  
160                                0                    0               0  
161                                0                    0               0  

[160 rows x 5 columns]

In [10]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [11]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
157      Male      31               Mumbai                   Never married
158    Female      42                Delhi             Was married earlier
159      Male      29              Mumbai                    Never married
160    Female      29              Gurgaon                   Never married
161      Male      31            New Delhi  Separated, filed for a divorce

[160 rows x 4 columns]

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [13]:
dataset

My Gender  My age My city of residence  My current relationship status
2        Male      32               Mumbai  Separated, filed for a divorce
3        Male      36           New Delhi                    Never married
4        Male      32           Bangalore                    Never married
5      Female      33             Gurugram             Was married earlier
6      Female      32               Mumbai                   Never married
..        ...     ...                  ...                             ...
157      Male      31               Mumbai                   Never married
158    Female      42                Delhi             Was married earlier
159      Male      29              Mumbai                    Never married
160    Female      29              Gurgaon                   Never married
161      Male      31            New Delhi  Separated, filed for a divorce

[160 rows x 4 columns]

In [14]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [16]:
print(features.shape)

(160, 43)


In [17]:
k =100
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=100)

In [18]:
row =9
selectedRow = refDataset.iloc[row]

In [19]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[  9 152 146  22  33 147  89 140 129   2  69  96  68  17  18  15 137  70
   57 154  16  30  93   5 115  27  14  10 132 133  46 130 153  40  49  85
   83 101  75 107  60  44 103   1  97 119  53  35   7 118 155 151 141  63
   38 149 143 150  81  91 157 128  66 121  77  73  50 105  99  48 114 122
    6 145 127   4 106 131  34 117   8 144  94  79 158  98  71  87  47  25
  159   0  82  52  20 125 148  67  28  90]]


In [20]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Female' 35 'Bangalore ' 'Never married']


['Female' 35 'Bangalore' 'Never married']


['Female' 34 'Bangalore' 'Never married']


['Female' 33 'Bangalore ' 'Never married']


['Female' 33 'Bangalore' 'Never married']


['Female' 31 'Bangalore ' 'Never married']


['Female' 31 'Bangalore' 'Never married']


['Female' 30 'Bangalore' 'Never married']


['Female' 29 'Bangalore/ Chennai ' 'Never married']


['Female' 42 'Bangalore ' 'Never married']


['Female' 33 'Delhi' 'Never married']


['Female' 33 'Mumbai' 'Never married']


['Female' 33 'Gurgaon' 'Never married']


['Female' 32 'Mumbai' 'Never married']


['Female' 32 'Delhi' 'Never married']


['Female' 34 'Chicago, IL' 'Never married']


['Female' 34 'Bangalore' 'Was married earlier']


['Female' 34 'Gurgaon' 'Never married']


['Female' 34 'Bikaner ' 'Never married']


['Female' 31 'Gurugram' 'Never married']


['Female' 35 'Gurugram' 'Never married']


['Female' 35 'Hyderabad ' 'Never married']


['Female' 29 'Gurgaon' 'Never 

In [ ]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [ ]:
print(preprocessData(refDataset))

In [21]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']