In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age My city of residence  \
0        Male      33               Mumbai   
1        Male      36           New Delhi    
2        Male      32           Bangalore    
3      Female      33             Gurugram   
4      Female      32               Mumbai   
..        ...     ...                  ...   
463    Female      37                Delhi   
464    Female      38            New delhi   
465    Female      38            Faridabad   
466      Male      32            New Delhi   
467    Female      37              Mumbai    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
0                                                                                                            
1                                                                                                            
2                                                                                                            
3                                                                                                            
4                                                                                                            
..                                                 ...                                                       
463                                                                                                          
464                                                                                                          
465                                                                                                          
466                                                                                                          
467                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
0                   Having things that money cant buy.                                                                                                                                                 
1                                      Family,friends                                                                                                                                                  
2                   Supportive/understandable/Friendly                                                                                                                                                 
3      Being able to love people and be loved by them                                                                                                                                                  
4      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
463  Able to take your own decisions, being financi...                                                                                                                                                 
464     Supportive family, friends and a well paid job                                                                                                                                                 
465  I view privilege as the profound gift of wakin...                                                                                                                                                 
466  Having a supportive family and being able to e...                                                                            

In [3]:
dataset.to_csv("dataset.csv")

In [4]:
dataset.index = np.arange(2, len(dataset) + 2)
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
465    Female      37                Delhi   
466    Female      38            New delhi   
467    Female      38            Faridabad   
468      Male      32            New Delhi   
469    Female      37              Mumbai    

    Video Introductions\n\n\n\nSubmit this if you  wish to share yours https://forms.gle/bvNGD2CcixYQV7sYA  \
2                                                                                                            
3                                                                                                            
4                                                                                                            
5                                                                                                            
6                                                                                                            
..                                                 ...                                                       
465                                                                                                          
466                                                                                                          
467                                                                                                          
468                                                                                                          
469                                                                                                          

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  the more detailed your response the more likely you will be asked for an introduction.  \
2                   Having things that money cant buy.                                                                                                                                                 
3                                      Family,friends                                                                                                                                                  
4                   Supportive/understandable/Friendly                                                                                                                                                 
5      Being able to love people and be loved by them                                                                                                                                                  
6      Being able to choose and make a life for myself                                                                                                                                                 
..                                                 ...                                                                                                                                                 
465  Able to take your own decisions, being financi...                                                                                                                                                 
466     Supportive family, friends and a well paid job                                                                                                                                                 
467  I view privilege as the profound gift of wakin...                                                                                                                                                 
468  Having a supportive family and being able to e...                                                                            

In [5]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

In [6]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
465    Female      37                Delhi   
466    Female      38            New delhi   
467    Female      38            Faridabad   
468      Male      32            New Delhi   
469    Female      37              Mumbai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
465                          Never married  
466  Was married earlier, legally divorced  
467  Was married earlier, legally divorced  
468                          Never married  
469                          Never married  

[468 rows x 4 columns]

In [7]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [9]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [10]:
encoded_categorical_features

Legally Separated  Never married  Separated, filed for a divorce  \
2                    1              0                               0   
3                    0              1                               0   
4                    0              1                               0   
5                    0              0                               0   
6                    0              1                               0   
..                 ...            ...                             ...   
465                  0              1                               0   
466                  0              0                               0   
467                  0              0                               0   
468                  0              1                               0   
469                  0              1                               0   

     Separated, not legally divorced  Was married earlier  \
2                                  0                    0   
3                                  0                    0   
4                                  0                    0   
5                                  0                    1   
6                                  0                    0   
..                               ...                  ...   
465                                0                    0   
466                                0                    0   
467                                0                    0   
468                                0                    0   
469                                0                    0   

     Was married earlier, legally divorced  Widow/ Widower  
2                                        0               0  
3                                        0               0  
4                                        0               0  
5                                        0               0  
6                                        0               0  
..                                     ...             ...  
465                                      0               0  
466                                      1               0  
467                                      1               0  
468                                      0               0  
469                                      0               0  

[468 rows x 7 columns]

In [11]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [12]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
465    Female      37                Delhi   
466    Female      38            New delhi   
467    Female      38            Faridabad   
468      Male      32            New Delhi   
469    Female      37              Mumbai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
465                          Never married  
466  Was married earlier, legally divorced  
467  Was married earlier, legally divorced  
468                          Never married  
469                          Never married  

[468 rows x 4 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [14]:
dataset

My Gender  My age My city of residence  \
2        Male      33               Mumbai   
3        Male      36           New Delhi    
4        Male      32           Bangalore    
5      Female      33             Gurugram   
6      Female      32               Mumbai   
..        ...     ...                  ...   
465    Female      37                Delhi   
466    Female      38            New delhi   
467    Female      38            Faridabad   
468      Male      32            New Delhi   
469    Female      37              Mumbai    

            My current relationship status  
2                        Legally Separated  
3                            Never married  
4                            Never married  
5                      Was married earlier  
6                            Never married  
..                                     ...  
465                          Never married  
466  Was married earlier, legally divorced  
467  Was married earlier, legally divorced  
468                          Never married  
469                          Never married  

[468 rows x 4 columns]

In [15]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [17]:
print(features.shape)

(468, 163)


In [18]:
k =280
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=280)

In [19]:
row =210
selectedRow = refDataset.iloc[row]

In [20]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[210 220 113 401 109 252 409 424 463 396 316  11 108 460 372 272  45 266
  165 342 440  25 313 331 320  41 330 385 278 383 332 326 343 245 247 290
  261 156 351  48  24 311  81 229 386  26 425 358 309 139 452 449 181 256
  354 363 333 123 288 118  97  51 122  30 390  54 128 295 110 376 462 262
   86 136 412  84 454 349 414 260 381  19 231  75 259  55 325 274 446 336
  310 307 114 365 393 183  42 375 265 287 355 308 200  52 415 353   1  27
  174 100 378  32 105 441 456  50 447  18 404  73   6 457 185 327  29 228
   12  65 251 111 344 258 301 178 453 221 291 282 467 373 246 388  96 420
   66 166  77 121 296 435 406 443 345  83 201 348 244  56 135 380 237 196
  169 428  36 411 106 328 160 209 340 432 143  91  89 241 194 208 255 171
  163 219 335 357  71 379 421 107 321 352 230 464  76 184 314 438 104  21
  112 271 264 238  35 413 382 211 142 147 119 205 214 442 422 249 173 403
  408 263  53 444 242 141  94 191  70 137  79 391  62  23 315 180  59  37
  297 346 188 426 405 101 257   9 429 

In [21]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Male' 43 'Delhi' 'Never married']


['Male' 47 'New Delhi ' 'Never married']


['Male' 42 'New Delhi ' 'Never married']


['Male' 55 'Dubai ' 'Never married']


['Male' 54 'Delhi ' 'Was married earlier']


['Male' 50 'Delhi ' 'Separated, not legally divorced']


['Male' 49 'Bangalore, Karnataka, India' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 49 'Pune' 'Never married']


['Male' 45 'Delhi ' 'Was married earlier']


['Male' 45 'Mumbai ' 'Never married']


['Male' 37 'Delhi' 'Never married']


['Male' 44 'Delhi' 'Widow/ Widower']


['Male' 44 'Delhi' 'Was married earlier']


['Male' 49 'New Delhi ' 'Was married earlier']


['Male' 43 'Mumbai ' 'Never married']


['Male' 43 'Tiruvalla ' 'Never married']


['Male' 43 'Delhi' 'Was married earlier']


['Male' 36 'Delhi' 'Never married']


['Male' 36 'Delhi ' 'Never married']


['Male' 42 'Mumbai' 'Never married']


['Male' 42 'Bangalore ' 'Never married']


['Male' 38 'New Delhi' 'Never married']


['Male' 38 'New De

In [22]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,6])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [23]:
print(preprocessData(refDataset))

[[ 1.         -0.73868015  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.23375954  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.90698701  0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.1028542   0.         ...  0.          0.
   0.        ]
 [ 1.         -0.90698701  0.         ...  0.          0.
   0.        ]
 [ 0.         -0.06545267  0.         ...  0.          0.
   0.        ]]


In [24]:
joblib.dump(knn, 'simpleclassifier.joblib')

['simpleclassifier.joblib']