In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

In [2]:
dataurl = 'https://docs.google.com/spreadsheets/d/1EmeVCJzCiMISggPuS5clv-gz4mznq24NMyFV8aXkbK4/edit?gid=0#gid=0'
dataurl = dataurl.replace('/edit?gid=', '/export?format=csv&gid=')
dataset = pd.read_csv(dataurl)
dataset = dataset.fillna('')
refDataset = dataset
dataset

My Gender  My age  My city of residence  \
0        Male      32                Mumbai   
1        Male      36            New Delhi    
2        Male      32            Bangalore    
3      Female      33              Gurugram   
4      Female      32                Mumbai   
..        ...     ...                   ...   
129      Male      32             Bangalore   
130      Male      34              Gurgaon    
131    Female      34           Chicago, IL   
132      Male      34                  Pune   
133      Male      34  RAJKOT ( GUJARAT  )    

    I define privilege to be (having a supportive family, dependable friends, a job you love, anything else)  \
0                   Having things that money cant buy.                                                         
1                                      Family,friends                                                          
2                   Supportive/understandable/Friendly                                                         
3      Being able to love people and be loved by them                                                          
4      Being able to choose and make a life for myself                                                         
..                                                 ...                                                         
129                                 Supportive family.                                                         
130          Having food, roof and family and friends                                                          
131  Having open communication with family and frie...                                                         
132  Supportive family and friends, healthy life an...                                                         
133  Cool family super cool friends coolest busines...                                                         

    About my growing up years  (they were awesome, they were challenging but all is good now, about the family, about friends, memories etc etc)  \
0    Defense upbringing, kept moving cities and sch...                                                                                             
1                                             Awesome                                                                                              
2                 Awesome & challenging, All Good Now.                                                                                             
3    We’re full of curiosity and learning I was an ...                                                                                             
4    Coming from a humble background, it has taught...                                                                                             
..                                                 ...                                                                                             
129                         My life is bit challenging                                                                                             
130  I was very shy till school but changed drastic...                                                                                             
131  I love my family, whatever they could do from ...                                                                                             
132  Life has taught me everything as i was growing...                                                                                             
133  Probably the best no complaints no regrets GOD...                                                                                             

     My current relationship status I have children  \
0    Separated, filed for a divorce              No   
1                     Never married              No   
2                     Never married              No   
3               Was married earlier              No   
4                     Never married       

In [3]:
dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

In [4]:
dataset

My Gender  My age  My city of residence  My current relationship status
0        Male      32                Mumbai  Separated, filed for a divorce
1        Male      36            New Delhi                    Never married
2        Male      32            Bangalore                    Never married
3      Female      33              Gurugram             Was married earlier
4      Female      32                Mumbai                   Never married
..        ...     ...                   ...                             ...
129      Male      32             Bangalore                   Never married
130      Male      34              Gurgaon                    Never married
131    Female      34           Chicago, IL                   Never married
132      Male      34                  Pune                   Never married
133      Male      34  RAJKOT ( GUJARAT  )                    Never married

[134 rows x 4 columns]

In [ ]:
age_weight =2.0
relationship_weight = 1.5
city_weight = 1.0


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

In [6]:
# one hot encoding
encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

In [7]:
encoded_categorical_features

Never married  Separated, filed for a divorce  \
0                0                               1   
1                1                               0   
2                1                               0   
3                0                               0   
4                1                               0   
..             ...                             ...   
129              1                               0   
130              1                               0   
131              1                               0   
132              1                               0   
133              1                               0   

     Separated, not legally divorced  Was married earlier  Widow/ Widower  
0                                  0                    0               0  
1                                  0                    0               0  
2                                  0                    0               0  
3                                  0                    1               0  
4                                  0                    0               0  
..                               ...                  ...             ...  
129                                0                    0               0  
130                                0                    0               0  
131                                0                    0               0  
132                                0                    0               0  
133                                0                    0               0  

[134 rows x 5 columns]

In [8]:
#label encode gender

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

In [9]:
dataset

My Gender  My age  My city of residence  My current relationship status
0        Male      32                Mumbai  Separated, filed for a divorce
1        Male      36            New Delhi                    Never married
2        Male      32            Bangalore                    Never married
3      Female      33              Gurugram             Was married earlier
4      Female      32                Mumbai                   Never married
..        ...     ...                   ...                             ...
129      Male      32             Bangalore                   Never married
130      Male      34              Gurgaon                    Never married
131    Female      34           Chicago, IL                   Never married
132      Male      34                  Pune                   Never married
133      Male      34  RAJKOT ( GUJARAT  )                    Never married

[134 rows x 4 columns]

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

In [11]:
dataset

My Gender  My age  My city of residence  My current relationship status
0        Male      32                Mumbai  Separated, filed for a divorce
1        Male      36            New Delhi                    Never married
2        Male      32            Bangalore                    Never married
3      Female      33              Gurugram             Was married earlier
4      Female      32                Mumbai                   Never married
..        ...     ...                   ...                             ...
129      Male      32             Bangalore                   Never married
130      Male      34              Gurgaon                    Never married
131    Female      34           Chicago, IL                   Never married
132      Male      34                  Pune                   Never married
133      Male      34  RAJKOT ( GUJARAT  )                    Never married

[134 rows x 4 columns]

In [12]:
labeledFeatures=labeledFeatures.reshape(-1,1)

print(city_vectorized.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
# prepare the data for training
features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized.toarray()])


In [14]:
k =100
knn = NearestNeighbors(n_neighbors=k, metric='cosine')
knn.fit(features)

NearestNeighbors(metric='cosine', n_neighbors=100)

In [17]:
row =9
selectedRow = refDataset.iloc[row]

In [18]:
distances, indices = knn.kneighbors(features[row].reshape(1,-1))
print(indices)

[[  9  22  33  89   2 129  69  96  17  93  68  18  15  70  57  16   5  30
  115 130  10  14  46  27 133 132  85  49  40  83  75 101  44 107 103  60
   63   1   7 118  53  97 119  35  38  81  91 121 128  66  77  50 105  73
   99 114  48 106   4   6 127 122  34   8 117 131  98  94  79  71  47  87
    0  82  25  20 125  52  90  67  64  28  92 102 116  39 109 123 124  95
  113  23  61  76  62  29  31  58  74   3]]


In [19]:
for i in indices[0]:
    if(dataset.iloc[i]['My Gender'] == selectedRow["My Gender"]):
        continue
    print(dataset.iloc[i].values)
    print("")
    print("")


['Female' 35 'Bangalore' 'Never married']


['Female' 34 'Bangalore' 'Never married']


['Female' 33 'Bangalore' 'Never married']


['Female' 31 'Bangalore' 'Never married']


['Female' 30 'Bangalore' 'Never married']


['Female' 29 'Bangalore/ Chennai ' 'Never married']


['Female' 42 'Bangalore ' 'Never married']


['Female' 32 'Delhi' 'Never married']


['Female' 32 'Mumbai' 'Never married']


['Female' 33 'Delhi' 'Never married']


['Female' 33 'Gurgaon' 'Never married']


['Female' 34 'Bangalore' 'Was married earlier']


['Female' 34 'Bikaner ' 'Never married']


['Female' 34 'Gurgaon' 'Never married']


['Female' 34 'Chicago, IL' 'Never married']


['Female' 29 'Bangalore' 'Was married earlier']


['Female' 35 'Gurugram' 'Never married']


['Female' 35 'Hyderabad ' 'Never married']


['Female' 36 'Bengaluru' 'Never married']


['Female' 36 'Bangalore ' 'Was married earlier']


['Female' 36 'Bangalore' 'Was married earlier']


['Female' 45 'Bangalore ' 'Never married']


['Female'

In [22]:
def preprocessData(dataset):
    dataset = (dataset.iloc[:,:3]).join(dataset.iloc[:,5])

    vectorizer = TfidfVectorizer()
    city_vectorized = vectorizer.fit_transform(dataset['My city of residence'])

    # one hot encoding
    encoded_categorical_features =  (pd.get_dummies(dataset['My current relationship status'], dtype=int))

    #label encode
    labelencoder = LabelEncoder()
    labeledFeatures = labelencoder.fit_transform(dataset['My Gender'])

    scaler = StandardScaler()
    scaled_numerical_features= scaler.fit_transform((dataset.iloc[:,1].values).reshape(-1,1))

    labeledFeatures=labeledFeatures.reshape(-1,1)
    city_vectorized = city_vectorized.toarray()

    features = np.hstack([labeledFeatures, scaled_numerical_features, encoded_categorical_features.values, city_vectorized])
    return features

In [23]:
print(preprocessData(refDataset))

[[ 1.         -1.02096198  0.         ...  0.          0.
   0.        ]
 [ 1.         -0.29034032  1.         ...  0.          0.
   0.        ]
 [ 1.         -1.02096198  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.65565115  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.65565115  1.         ...  0.          0.
   0.        ]
 [ 1.         -0.65565115  1.         ...  0.          0.
   0.        ]]


In [ ]:
joblib.dump(knn, 'simpleclassifier.joblib')